### PR TITLE
NetworkTest

### PR DESCRIPTION
**Pull request by kartpat**
Thought we could merge and make this main. This was the last functional build we used for demo.

### CODE REVIEW

**Comment by popabczhang** [comment]
it says "This branch has no conflicts with the base branch
Merging can be performed automatically." 
Should we do it?

**Comment by kartpat** [comment]
Yes go ahead!

**Comment by kartpat** [comment]
Let me try the new build after the merge to check if things are still working.

**Comment by popabczhang** [comment]
Cool, is it working after merge?

**Comment by kartpat** [comment]
I tried, it does not show up on the hierarchy. Is there a different scene that I should try loading? You can try opening the file at your end as well.

**Comment by popabczhang** [comment]
I just tried. The new master branch works exactly like the NetworkTest branch now. It opened and built the APK. Of course I didn't try the APK, since I don't have a tango with me.

**Comment by kartpat** [comment]
Oh right! Sorry, I thought we were combining the the assets from new assets that you made from rhino in the muso+ryan branch. My mistake! great it's working

**Comment by popabczhang** [comment]
cool, first merge success. let's looking for the more challenging ones
soon.

**Pull request merged**
